### ISSUE TITLE
problem getting saved_model.pb

### ISSUE THREAD

**Issue by vidalmaxime** [DLTK/models#12]
Hello,

I ran train.py on my own data and got all the necessary files (.ckpt, checkpoint, graph.pbtxt) in MODEL_PATH. However, this does not provide me with the saved_model.pb file which is necessary in order to run deploy.py. I was wondering if you could share the code as to how to transform the output of train.py into the saved_model.pb.

Thanks a lot !

**Comment by mrajchl** [comment]
Hi,
please refer to this closed issue:
https://github.com/DLTK/models/issues/11
This should do it.

**Comment by vidalmaxime** [comment]
Thanks, but that's not the same issue. He is deploying the downloaded neuronet, whereas I have trained on my own data using the neuronet architecture.  So i'm not trying to find the path to saved_model.pb, but rather to create it as it doesn't exist once I do train.py

**Comment by mrajchl** [comment]
This is where the model is exported: https://github.com/DLTK/models/blob/master/ukbb_neuronet_brain_segmentation/train.py#L181

If you break the training loop with CTRL+C, it will be triggered too. Is that what you mean? The downloaded models are produced as is from train.py

**Comment by vidalmaxime** [comment]
Yes, the files produced by this line of code are : checkpoint, events.out.tfevents, model.ckpt.index, model.ckpt.data, model.ckpt.meta, and graph.pbtxt. However, deploy.py requires 'saved_model.pb' which is not created inside train.py. It is however included in the downloaded models. I am trying to create it.

**Comment by mrajchl** [comment]
No, these files are created during training with the estimator train func (c.f. https://github.com/DLTK/models/blob/master/ukbb_neuronet_brain_segmentation/train.py#L168). The above line should export the model AFAIR. In order to trigger it, you will either need to: 
a) Stop the iterations with CTRL+C, triggering the line here: https://github.com/DLTK/models/blob/master/ukbb_neuronet_brain_segmentation/train.py#L177
or 
b) let the training run to maximum iterations. 

I am not entirely certain that you have done this. Let me know if that worked or visit us in our gitter chat (https://gitter.im/DLTK/DLTK).

**Comment by vidalmaxime** [comment]
Thanks a lot, I wrongly ended the training indeed.
