### ISSUE TITLE
Segmentation with neuronet fails

### ISSUE THREAD

**Issue by SaraDupont** [DLTK/models#9]
Hi ! I'm trying to use Neuronet to get white and gray matter and CSF segmentation on T1-w images. For one of the subjects I tried it works great but for 4 others the segmentation is incomplete (see screenshot below). 
I tried adding a gaussian denoising before (with different kernel sizes) and resampling to a 1x1x1 mm3 resolution without success. 
Any insight on how to make it robust enough to use this method in my processing?  (I don't have enough data to retrain a model myself.) 
Thank you !

<img width="1289" alt="screenshot 2018-07-06 10 15 31" src="https://user-images.githubusercontent.com/5857909/42392247-042625f2-8107-11e8-874b-2c28289135e8.png">

**Comment by mrajchl** [comment]
Hi Sara,
you will need to register to  the MNI atlas, so that your images are also in the correct orientation (not just 1mm isotropic resolution). This might be a source of error. Another might be the differences in contrast: One of the major issues currently with learning and inferring on T1w images, is that different imaging protocols cause differences in contrast. Generally, this is a domain adaption problem, where the images in your domain are different from those in the UKB training database. 

If the issue persists, your sequence might be too different from UKB and you will likely need to retrain/transfer learn in order to infer on your data. 
HTH

**Comment by fepegar** [comment]
> you will need to register to the MNI atlas

Would a rigid registration be enough?
